export const excelData = [
  {
    sucursal: "S103",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "21",
    subCanal1: "Almacen/Despensa",
    subCanal2: "Almacen/Despensa",
    codSubCanal1: "00",
    codSubCanal2: "00",
  },
  {
    sucursal: "S103",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "21",
    subCanal1: "Almacen/Despensa",
    subCanal2: "Reja/Ventana",
    codSubCanal1: "00",
    codSubCanal2: "01",
  },
  {
    sucursal: "S103",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "21",
    subCanal1: "Kioskos Y Casillas",
    subCanal2: "Kioskos Y Casillas",
    codSubCanal1: "02",
    codSubCanal2: "02",
  },
  {
    sucursal: "S103",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "21",
    subCanal1: "Autoservicio",
    subCanal2: "Autoservicio",
    codSubCanal1: "03",
    codSubCanal2: "03",
  },
  {
    sucursal: "S103",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "21",
    subCanal1: "Minimercado",
    subCanal2: "Minimercado",
    codSubCanal1: "04",
    codSubCanal2: "04",
  },
  {
    sucursal: "S103",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "21",
    subCanal1: "Fruteria/Verduleria",
    subCanal2: "Fruteria/Verduleria",
    codSubCanal1: "05",
    codSubCanal2: "05",
  },
  {
    sucursal: "S103",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "21",
    subCanal1: "Limpieza",
    subCanal2: "Productos Caseros",
    codSubCanal1: "06",
    codSubCanal2: "07",
  },
  {
    sucursal: "S103",
    codigo: "10",
    canal: "Mayorista",
    listaPrecio: "35",
    subCanal1: "Mayorista Con Reparto",
    subCanal2: "Mayorista Con Reparto",
    codSubCanal1: "00",
    codSubCanal2: "00",
  },
  {
    sucursal: "S103",
    codigo: "10",
    canal: "Mayorista",
    listaPrecio: "35",
    subCanal1: "Mayorista con salon de ventas",
    subCanal2: "Mayorista con salon de ventas",
    codSubCanal1: "01",
    codSubCanal2: "01",
  },
  {
    sucursal: "S103",
    codigo: "10",
    canal: "Mayorista",
    listaPrecio: "35",
    subCanal1: "Comercial",
    subCanal2: "Comercial",
    codSubCanal1: "02",
    codSubCanal2: "02",
  },
  {
    sucursal: "S103",
    codigo: "10",
    canal: "Mayorista",
    listaPrecio: "35",
    subCanal1: "Comercial con reparto",
    subCanal2: "Comercial con reparto",
    codSubCanal1: "03",
    codSubCanal2: "03",
  },
  {
    sucursal: "S103",
    codigo: "02",
    canal: "Supermercado",
    listaPrecio: "45",
    subCanal1: "Skm Cadenas",
    subCanal2: "Skm Cadenas",
    codSubCanal1: "00",
    codSubCanal2: "00",
  },
  {
    sucursal: "S103",
    codigo: "02",
    canal: "Supermercado",
    listaPrecio: "45",
    subCanal1: "Skm independiente",
    subCanal2: "Skm independiente",
    codSubCanal1: "23",
    codSubCanal2: "23",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Hoteles",
    subCanal2: "Hoteles",
    codSubCanal1: "00",
    codSubCanal2: "00",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Moteles",
    subCanal2: "Moteles",
    codSubCanal1: "01",
    codSubCanal2: "01",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Posada",
    subCanal2: "Posada",
    codSubCanal1: "02",
    codSubCanal2: "02",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Lavanderias",
    subCanal2: "Lavanderias",
    codSubCanal1: "03",
    codSubCanal2: "03",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Estacion de servicio",
    subCanal2: "Estacion de servicio",
    codSubCanal1: "04",
    codSubCanal2: "04",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Farmacia",
    subCanal2: "Farmacia",
    codSubCanal1: "05",
    codSubCanal2: "05",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Veterinaria",
    subCanal2: "Veterinaria",
    codSubCanal1: "06",
    codSubCanal2: "06",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Spa-Peluquerias",
    subCanal2: "Spa-Peluquerias",
    codSubCanal1: "07",
    codSubCanal2: "07",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Empleados",
    subCanal2: "Empleados",
    codSubCanal1: "08",
    codSubCanal2: "08",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Club Social",
    subCanal2: "Club Social",
    codSubCanal1: "09",
    codSubCanal2: "09",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Hospitales/ Sanatorios",
    subCanal2: "Hospital",
    codSubCanal1: "10",
    codSubCanal2: "10",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Hospitales/ Sanatorios",
    subCanal2: "Sanatorio",
    codSubCanal1: "10",
    codSubCanal2: "11",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Instituciones",
    subCanal2: "Colegio",
    codSubCanal1: "12",
    codSubCanal2: "12",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Instituciones",
    subCanal2: "Guarderia",
    codSubCanal1: "12",
    codSubCanal2: "13",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Instituciones",
    subCanal2: "Escuela",
    codSubCanal1: "12",
    codSubCanal2: "14",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Instituciones",
    subCanal2: "Iglesia",
    codSubCanal1: "12",
    codSubCanal2: "15",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Instituciones",
    subCanal2: "Fundacion",
    codSubCanal1: "12",
    codSubCanal2: "16",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Empresas",
    subCanal2: "Limpieza",
    codSubCanal1: "17",
    codSubCanal2: "17",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Empresas",
    subCanal2: "Banco",
    codSubCanal1: "17",
    codSubCanal2: "18",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Empresas",
    subCanal2: "Cooperativa",
    codSubCanal1: "17",
    codSubCanal2: "19",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Empresas",
    subCanal2: "Fabrica",
    codSubCanal1: "17",
    codSubCanal2: "20",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Empresas",
    subCanal2: "Materiales de Construccion",
    codSubCanal1: "17",
    codSubCanal2: "21",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Bar",
    codSubCanal1: "22",
    codSubCanal2: "22",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Cafeteria",
    codSubCanal1: "22",
    codSubCanal2: "23",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Cantina",
    codSubCanal1: "22",
    codSubCanal2: "24",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Comedor",
    codSubCanal1: "22",
    codSubCanal2: "25",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Copetin",
    codSubCanal1: "22",
    codSubCanal2: "26",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Restaurant",
    codSubCanal1: "22",
    codSubCanal2: "27",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Otros",
    subCanal2: "Bodega",
    codSubCanal1: "28",
    codSubCanal2: "28",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Otros",
    subCanal2: "Carniceria",
    codSubCanal1: "28",
    codSubCanal2: "29",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Otros",
    subCanal2: "Consumidor Final",
    codSubCanal1: "28",
    codSubCanal2: "30",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Otros",
    subCanal2: "Consumo Interno",
    codSubCanal1: "28",
    codSubCanal2: "31",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Otros",
    subCanal2: "Ferreteria",
    codSubCanal1: "28",
    codSubCanal2: "32",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Otros",
    subCanal2: "Gomeria",
    codSubCanal1: "28",
    codSubCanal2: "33",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Otros",
    subCanal2: "Hamburgeseria",
    codSubCanal1: "28",
    codSubCanal2: "34",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Otros",
    subCanal2: "Heladeria",
    codSubCanal1: "28",
    codSubCanal2: "35",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Otros",
    subCanal2: "Librería",
    codSubCanal1: "28",
    codSubCanal2: "36",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Otros",
    subCanal2: "Merceria",
    codSubCanal1: "28",
    codSubCanal2: "37",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Otros",
    subCanal2: "Panaderia",
    codSubCanal1: "28",
    codSubCanal2: "38",
  },
  {
    sucursal: "S103",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "21",
    subCanal1: "Otros",
    subCanal2: "Taller",
    codSubCanal1: "28",
    codSubCanal2: "39",
  },
  {
    sucursal: "S101",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "22",
    subCanal1: "Almacen/Despensa",
    subCanal2: "Almacen/Despensa",
    codSubCanal1: "00",
    codSubCanal2: "00",
  },
  {
    sucursal: "S101",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "22",
    subCanal1: "Almacen/Despensa",
    subCanal2: "Reja/Ventana",
    codSubCanal1: "00",
    codSubCanal2: "01",
  },
  {
    sucursal: "S101",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "22",
    subCanal1: "Kioskos Y Casillas",
    subCanal2: "Kioskos Y Casillas",
    codSubCanal1: "02",
    codSubCanal2: "02",
  },
  {
    sucursal: "S101",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "22",
    subCanal1: "Autoservicio",
    subCanal2: "Autoservicio",
    codSubCanal1: "03",
    codSubCanal2: "03",
  },
  {
    sucursal: "S101",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "22",
    subCanal1: "Minimercado",
    subCanal2: "Minimercado",
    codSubCanal1: "04",
    codSubCanal2: "04",
  },
  {
    sucursal: "S101",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "22",
    subCanal1: "Fruteria/Verduleria",
    subCanal2: "Fruteria/Verduleria",
    codSubCanal1: "05",
    codSubCanal2: "05",
  },
  {
    sucursal: "S101",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "22",
    subCanal1: "Limpieza",
    subCanal2: "Productos Caseros",
    codSubCanal1: "06",
    codSubCanal2: "07",
  },
  {
    sucursal: "S101",
    codigo: "10",
    canal: "Mayorista",
    listaPrecio: "25",
    subCanal1: "Mayorista Con Reparto",
    subCanal2: "Mayorista Con Reparto",
    codSubCanal1: "00",
    codSubCanal2: "00",
  },
  {
    sucursal: "S101",
    codigo: "10",
    canal: "Mayorista",
    listaPrecio: "25",
    subCanal1: "Mayorista con salon de ventas",
    subCanal2: "Mayorista con salon de ventas",
    codSubCanal1: "01",
    codSubCanal2: "01",
  },
  {
    sucursal: "S101",
    codigo: "10",
    canal: "Mayorista",
    listaPrecio: "25",
    subCanal1: "Comercial",
    subCanal2: "Comercial",
    codSubCanal1: "02",
    codSubCanal2: "02",
  },
  {
    sucursal: "S101",
    codigo: "10",
    canal: "Mayorista",
    listaPrecio: "25",
    subCanal1: "Comercial con reparto",
    subCanal2: "Comercial con reparto",
    codSubCanal1: "03",
    codSubCanal2: "03",
  },
  {
    sucursal: "S101",
    codigo: "02",
    canal: "Supermercado",
    listaPrecio: "43",
    subCanal1: "Skm Cadenas",
    subCanal2: "Skm Cadenas",
    codSubCanal1: "00",
    codSubCanal2: "00",
  },
  {
    sucursal: "S101",
    codigo: "02",
    canal: "Supermercado",
    listaPrecio: "43",
    subCanal1: "Skm independiente",
    subCanal2: "Skm independiente",
    codSubCanal1: "23",
    codSubCanal2: "23",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Hoteles",
    subCanal2: "Hoteles",
    codSubCanal1: "00",
    codSubCanal2: "00",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Moteles",
    subCanal2: "Moteles",
    codSubCanal1: "01",
    codSubCanal2: "01",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Posada",
    subCanal2: "Posada",
    codSubCanal1: "02",
    codSubCanal2: "02",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Lavanderias",
    subCanal2: "Lavanderias",
    codSubCanal1: "03",
    codSubCanal2: "03",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Estacion de servicio",
    subCanal2: "Estacion de servicio",
    codSubCanal1: "04",
    codSubCanal2: "04",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Farmacia",
    subCanal2: "Farmacia",
    codSubCanal1: "05",
    codSubCanal2: "05",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Veterinaria",
    subCanal2: "Veterinaria",
    codSubCanal1: "06",
    codSubCanal2: "06",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Spa-Peluquerias",
    subCanal2: "Spa-Peluquerias",
    codSubCanal1: "07",
    codSubCanal2: "07",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Empleados",
    subCanal2: "Empleados",
    codSubCanal1: "08",
    codSubCanal2: "08",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Club Social",
    subCanal2: "Club Social",
    codSubCanal1: "09",
    codSubCanal2: "09",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Hospitales/ Sanatorios",
    subCanal2: "Hospital",
    codSubCanal1: "10",
    codSubCanal2: "10",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Hospitales/ Sanatorios",
    subCanal2: "Sanatorio",
    codSubCanal1: "10",
    codSubCanal2: "11",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Instituciones",
    subCanal2: "Colegio",
    codSubCanal1: "12",
    codSubCanal2: "12",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Instituciones",
    subCanal2: "Guarderia",
    codSubCanal1: "12",
    codSubCanal2: "13",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Instituciones",
    subCanal2: "Escuela",
    codSubCanal1: "12",
    codSubCanal2: "14",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Instituciones",
    subCanal2: "Iglesia",
    codSubCanal1: "12",
    codSubCanal2: "15",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Instituciones",
    subCanal2: "Fundacion",
    codSubCanal1: "12",
    codSubCanal2: "16",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Empresas",
    subCanal2: "Limpieza",
    codSubCanal1: "17",
    codSubCanal2: "17",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Empresas",
    subCanal2: "Banco",
    codSubCanal1: "17",
    codSubCanal2: "18",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Empresas",
    subCanal2: "Cooperativa",
    codSubCanal1: "17",
    codSubCanal2: "19",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Empresas",
    subCanal2: "Fabrica",
    codSubCanal1: "17",
    codSubCanal2: "20",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Empresas",
    subCanal2: "Materiales de Construccion",
    codSubCanal1: "17",
    codSubCanal2: "21",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Bar",
    codSubCanal1: "22",
    codSubCanal2: "22",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Cafeteria",
    codSubCanal1: "22",
    codSubCanal2: "23",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Cantina",
    codSubCanal1: "22",
    codSubCanal2: "24",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Comedor",
    codSubCanal1: "22",
    codSubCanal2: "25",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Copetin",
    codSubCanal1: "22",
    codSubCanal2: "26",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Restaurant",
    codSubCanal1: "22",
    codSubCanal2: "27",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Otros",
    subCanal2: "Bodega",
    codSubCanal1: "28",
    codSubCanal2: "28",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Otros",
    subCanal2: "Carniceria",
    codSubCanal1: "28",
    codSubCanal2: "29",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Otros",
    subCanal2: "Consumidor Final",
    codSubCanal1: "28",
    codSubCanal2: "30",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Otros",
    subCanal2: "Consumo Interno",
    codSubCanal1: "28",
    codSubCanal2: "31",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Otros",
    subCanal2: "Ferreteria",
    codSubCanal1: "28",
    codSubCanal2: "32",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Otros",
    subCanal2: "Gomeria",
    codSubCanal1: "28",
    codSubCanal2: "33",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Otros",
    subCanal2: "Hamburgeseria",
    codSubCanal1: "28",
    codSubCanal2: "34",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Otros",
    subCanal2: "Heladeria",
    codSubCanal1: "28",
    codSubCanal2: "35",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Otros",
    subCanal2: "Librería",
    codSubCanal1: "28",
    codSubCanal2: "36",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Otros",
    subCanal2: "Merceria",
    codSubCanal1: "28",
    codSubCanal2: "37",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Otros",
    subCanal2: "Panaderia",
    codSubCanal1: "28",
    codSubCanal2: "38",
  },
  {
    sucursal: "S101",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "22",
    subCanal1: "Otros",
    subCanal2: "Taller",
    codSubCanal1: "28",
    codSubCanal2: "39",
  },
  {
    sucursal: "S102",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "26",
    subCanal1: "Almacen/Despensa",
    subCanal2: "Almacen/Despensa",
    codSubCanal1: "00",
    codSubCanal2: "00",
  },
  {
    sucursal: "S102",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "26",
    subCanal1: "Almacen/Despensa",
    subCanal2: "Reja/Ventana",
    codSubCanal1: "00",
    codSubCanal2: "01",
  },
  {
    sucursal: "S102",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "26",
    subCanal1: "Kioskos Y Casillas",
    subCanal2: "Kioskos Y Casillas",
    codSubCanal1: "02",
    codSubCanal2: "02",
  },
  {
    sucursal: "S102",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "26",
    subCanal1: "Autoservicio",
    subCanal2: "Autoservicio",
    codSubCanal1: "03",
    codSubCanal2: "03",
  },
  {
    sucursal: "S102",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "26",
    subCanal1: "Minimercado",
    subCanal2: "Minimercado",
    codSubCanal1: "04",
    codSubCanal2: "04",
  },
  {
    sucursal: "S102",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "26",
    subCanal1: "Fruteria/Verduleria",
    subCanal2: "Fruteria/Verduleria",
    codSubCanal1: "05",
    codSubCanal2: "05",
  },
  {
    sucursal: "S102",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "26",
    subCanal1: "Limpieza",
    subCanal2: "Productos Caseros",
    codSubCanal1: "06",
    codSubCanal2: "07",
  },
  {
    sucursal: "S102",
    codigo: "10",
    canal: "Mayorista",
    listaPrecio: "38",
    subCanal1: "Mayorista Con Reparto",
    subCanal2: "Mayorista Con Reparto",
    codSubCanal1: "00",
    codSubCanal2: "00",
  },
  {
    sucursal: "S102",
    codigo: "10",
    canal: "Mayorista",
    listaPrecio: "38",
    subCanal1: "Mayorista con salon de ventas",
    subCanal2: "Mayorista con salon de ventas",
    codSubCanal1: "01",
    codSubCanal2: "01",
  },
  {
    sucursal: "S102",
    codigo: "10",
    canal: "Mayorista",
    listaPrecio: "38",
    subCanal1: "Comercial",
    subCanal2: "Comercial",
    codSubCanal1: "02",
    codSubCanal2: "02",
  },
  {
    sucursal: "S102",
    codigo: "10",
    canal: "Mayorista",
    listaPrecio: "38",
    subCanal1: "Comercial con reparto",
    subCanal2: "Comercial con reparto",
    codSubCanal1: "03",
    codSubCanal2: "03",
  },
  {
    sucursal: "S102",
    codigo: "02",
    canal: "Supermercado",
    listaPrecio: "44",
    subCanal1: "Skm Cadenas",
    subCanal2: "Skm Cadenas",
    codSubCanal1: "00",
    codSubCanal2: "00",
  },
  {
    sucursal: "S102",
    codigo: "02",
    canal: "Supermercado",
    listaPrecio: "44",
    subCanal1: "Skm independiente",
    subCanal2: "Skm independiente",
    codSubCanal1: "23",
    codSubCanal2: "23",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Hoteles",
    subCanal2: "Hoteles",
    codSubCanal1: "00",
    codSubCanal2: "00",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Moteles",
    subCanal2: "Moteles",
    codSubCanal1: "01",
    codSubCanal2: "01",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Posada",
    subCanal2: "Posada",
    codSubCanal1: "02",
    codSubCanal2: "02",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Lavanderias",
    subCanal2: "Lavanderias",
    codSubCanal1: "03",
    codSubCanal2: "03",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Estacion de servicio",
    subCanal2: "Estacion de servicio",
    codSubCanal1: "04",
    codSubCanal2: "04",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Farmacia",
    subCanal2: "Farmacia",
    codSubCanal1: "05",
    codSubCanal2: "05",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Veterinaria",
    subCanal2: "Veterinaria",
    codSubCanal1: "06",
    codSubCanal2: "06",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Spa-Peluquerias",
    subCanal2: "Spa-Peluquerias",
    codSubCanal1: "07",
    codSubCanal2: "07",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Empleados",
    subCanal2: "Empleados",
    codSubCanal1: "08",
    codSubCanal2: "08",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Club Social",
    subCanal2: "Club Social",
    codSubCanal1: "09",
    codSubCanal2: "09",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Hospitales/ Sanatorios",
    subCanal2: "Hospital",
    codSubCanal1: "10",
    codSubCanal2: "10",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Hospitales/ Sanatorios",
    subCanal2: "Sanatorio",
    codSubCanal1: "10",
    codSubCanal2: "11",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Instituciones",
    subCanal2: "Colegio",
    codSubCanal1: "12",
    codSubCanal2: "12",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Instituciones",
    subCanal2: "Guarderia",
    codSubCanal1: "12",
    codSubCanal2: "13",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Instituciones",
    subCanal2: "Escuela",
    codSubCanal1: "12",
    codSubCanal2: "14",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Instituciones",
    subCanal2: "Iglesia",
    codSubCanal1: "12",
    codSubCanal2: "15",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Instituciones",
    subCanal2: "Fundacion",
    codSubCanal1: "12",
    codSubCanal2: "16",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Empresas",
    subCanal2: "Limpieza",
    codSubCanal1: "17",
    codSubCanal2: "17",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Empresas",
    subCanal2: "Banco",
    codSubCanal1: "17",
    codSubCanal2: "18",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Empresas",
    subCanal2: "Cooperativa",
    codSubCanal1: "17",
    codSubCanal2: "19",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Empresas",
    subCanal2: "Fabrica",
    codSubCanal1: "17",
    codSubCanal2: "20",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Empresas",
    subCanal2: "Materiales de Construccion",
    codSubCanal1: "17",
    codSubCanal2: "21",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Bar",
    codSubCanal1: "22",
    codSubCanal2: "22",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Cafeteria",
    codSubCanal1: "22",
    codSubCanal2: "23",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Cantina",
    codSubCanal1: "22",
    codSubCanal2: "24",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Comedor",
    codSubCanal1: "22",
    codSubCanal2: "25",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Copetin",
    codSubCanal1: "22",
    codSubCanal2: "26",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Restaurant",
    codSubCanal1: "22",
    codSubCanal2: "27",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Otros",
    subCanal2: "Bodega",
    codSubCanal1: "28",
    codSubCanal2: "28",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Otros",
    subCanal2: "Carniceria",
    codSubCanal1: "28",
    codSubCanal2: "29",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Otros",
    subCanal2: "Consumidor Final",
    codSubCanal1: "28",
    codSubCanal2: "30",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Otros",
    subCanal2: "Consumo Interno",
    codSubCanal1: "28",
    codSubCanal2: "31",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Otros",
    subCanal2: "Ferreteria",
    codSubCanal1: "28",
    codSubCanal2: "32",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Otros",
    subCanal2: "Gomeria",
    codSubCanal1: "28",
    codSubCanal2: "33",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Otros",
    subCanal2: "Hamburgeseria",
    codSubCanal1: "28",
    codSubCanal2: "34",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Otros",
    subCanal2: "Heladeria",
    codSubCanal1: "28",
    codSubCanal2: "35",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Otros",
    subCanal2: "Librería",
    codSubCanal1: "28",
    codSubCanal2: "36",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Otros",
    subCanal2: "Merceria",
    codSubCanal1: "28",
    codSubCanal2: "37",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Otros",
    subCanal2: "Panaderia",
    codSubCanal1: "28",
    codSubCanal2: "38",
  },
  {
    sucursal: "S102",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "26",
    subCanal1: "Otros",
    subCanal2: "Taller",
    codSubCanal1: "28",
    codSubCanal2: "39",
  },
  {
    sucursal: "S105",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "29",
    subCanal1: "Almacen/Despensa",
    subCanal2: "Almacen/Despensa",
    codSubCanal1: "00",
    codSubCanal2: "00",
  },
  {
    sucursal: "S105",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "29",
    subCanal1: "Almacen/Despensa",
    subCanal2: "Reja/Ventana",
    codSubCanal1: "00",
    codSubCanal2: "01",
  },
  {
    sucursal: "S105",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "29",
    subCanal1: "Kioskos Y Casillas",
    subCanal2: "Kioskos Y Casillas",
    codSubCanal1: "02",
    codSubCanal2: "02",
  },
  {
    sucursal: "S105",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "29",
    subCanal1: "Autoservicio",
    subCanal2: "Autoservicio",
    codSubCanal1: "03",
    codSubCanal2: "03",
  },
  {
    sucursal: "S105",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "29",
    subCanal1: "Minimercado",
    subCanal2: "Minimercado",
    codSubCanal1: "04",
    codSubCanal2: "04",
  },
  {
    sucursal: "S105",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "29",
    subCanal1: "Fruteria/Verduleria",
    subCanal2: "Fruteria/Verduleria",
    codSubCanal1: "05",
    codSubCanal2: "05",
  },
  {
    sucursal: "S105",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "29",
    subCanal1: "Limpieza",
    subCanal2: "Productos Caseros",
    codSubCanal1: "06",
    codSubCanal2: "07",
  },
  {
    sucursal: "S105",
    codigo: "10",
    canal: "Mayorista",
    listaPrecio: "33",
    subCanal1: "Mayorista Con Reparto",
    subCanal2: "Mayorista Con Reparto",
    codSubCanal1: "00",
    codSubCanal2: "00",
  },
  {
    sucursal: "S105",
    codigo: "10",
    canal: "Mayorista",
    listaPrecio: "33",
    subCanal1: "Mayorista con salon de ventas",
    subCanal2: "Mayorista con salon de ventas",
    codSubCanal1: "01",
    codSubCanal2: "01",
  },
  {
    sucursal: "S105",
    codigo: "10",
    canal: "Mayorista",
    listaPrecio: "33",
    subCanal1: "Comercial",
    subCanal2: "Comercial",
    codSubCanal1: "02",
    codSubCanal2: "02",
  },
  {
    sucursal: "S105",
    codigo: "10",
    canal: "Mayorista",
    listaPrecio: "33",
    subCanal1: "Comercial con reparto",
    subCanal2: "Comercial con reparto",
    codSubCanal1: "03",
    codSubCanal2: "03",
  },
  {
    sucursal: "S105",
    codigo: "02",
    canal: "Supermercado",
    listaPrecio: "48",
    subCanal1: "Skm Cadenas",
    subCanal2: "Skm Cadenas",
    codSubCanal1: "00",
    codSubCanal2: "00",
  },
  {
    sucursal: "S105",
    codigo: "02",
    canal: "Supermercado",
    listaPrecio: "48",
    subCanal1: "Skm independiente",
    subCanal2: "Skm independiente",
    codSubCanal1: "23",
    codSubCanal2: "23",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Hoteles",
    subCanal2: "Hoteles",
    codSubCanal1: "00",
    codSubCanal2: "00",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Moteles",
    subCanal2: "Moteles",
    codSubCanal1: "01",
    codSubCanal2: "01",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Posada",
    subCanal2: "Posada",
    codSubCanal1: "02",
    codSubCanal2: "02",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Lavanderias",
    subCanal2: "Lavanderias",
    codSubCanal1: "03",
    codSubCanal2: "03",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Estacion de servicio",
    subCanal2: "Estacion de servicio",
    codSubCanal1: "04",
    codSubCanal2: "04",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Farmacia",
    subCanal2: "Farmacia",
    codSubCanal1: "05",
    codSubCanal2: "05",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Veterinaria",
    subCanal2: "Veterinaria",
    codSubCanal1: "06",
    codSubCanal2: "06",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Spa-Peluquerias",
    subCanal2: "Spa-Peluquerias",
    codSubCanal1: "07",
    codSubCanal2: "07",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Empleados",
    subCanal2: "Empleados",
    codSubCanal1: "08",
    codSubCanal2: "08",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Club Social",
    subCanal2: "Club Social",
    codSubCanal1: "09",
    codSubCanal2: "09",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Hospitales/ Sanatorios",
    subCanal2: "Hospital",
    codSubCanal1: "10",
    codSubCanal2: "10",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Hospitales/ Sanatorios",
    subCanal2: "Sanatorio",
    codSubCanal1: "10",
    codSubCanal2: "11",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Instituciones",
    subCanal2: "Colegio",
    codSubCanal1: "12",
    codSubCanal2: "12",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Instituciones",
    subCanal2: "Guarderia",
    codSubCanal1: "12",
    codSubCanal2: "13",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Instituciones",
    subCanal2: "Escuela",
    codSubCanal1: "12",
    codSubCanal2: "14",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Instituciones",
    subCanal2: "Iglesia",
    codSubCanal1: "12",
    codSubCanal2: "15",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Instituciones",
    subCanal2: "Fundacion",
    codSubCanal1: "12",
    codSubCanal2: "16",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Empresas",
    subCanal2: "Limpieza",
    codSubCanal1: "17",
    codSubCanal2: "17",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Empresas",
    subCanal2: "Banco",
    codSubCanal1: "17",
    codSubCanal2: "18",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Empresas",
    subCanal2: "Cooperativa",
    codSubCanal1: "17",
    codSubCanal2: "19",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Empresas",
    subCanal2: "Fabrica",
    codSubCanal1: "17",
    codSubCanal2: "20",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Empresas",
    subCanal2: "Materiales de Construccion",
    codSubCanal1: "17",
    codSubCanal2: "21",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Bar",
    codSubCanal1: "22",
    codSubCanal2: "22",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Cafeteria",
    codSubCanal1: "22",
    codSubCanal2: "23",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Cantina",
    codSubCanal1: "22",
    codSubCanal2: "24",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Comedor",
    codSubCanal1: "22",
    codSubCanal2: "25",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Copetin",
    codSubCanal1: "22",
    codSubCanal2: "26",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Restaurant",
    codSubCanal1: "22",
    codSubCanal2: "27",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Otros",
    subCanal2: "Bodega",
    codSubCanal1: "28",
    codSubCanal2: "28",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Otros",
    subCanal2: "Carniceria",
    codSubCanal1: "28",
    codSubCanal2: "29",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Otros",
    subCanal2: "Consumidor Final",
    codSubCanal1: "28",
    codSubCanal2: "30",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Otros",
    subCanal2: "Consumo Interno",
    codSubCanal1: "28",
    codSubCanal2: "31",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Otros",
    subCanal2: "Ferreteria",
    codSubCanal1: "28",
    codSubCanal2: "32",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Otros",
    subCanal2: "Gomeria",
    codSubCanal1: "28",
    codSubCanal2: "33",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Otros",
    subCanal2: "Hamburgeseria",
    codSubCanal1: "28",
    codSubCanal2: "34",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Otros",
    subCanal2: "Heladeria",
    codSubCanal1: "28",
    codSubCanal2: "35",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Otros",
    subCanal2: "Librería",
    codSubCanal1: "28",
    codSubCanal2: "36",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Otros",
    subCanal2: "Merceria",
    codSubCanal1: "28",
    codSubCanal2: "37",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Otros",
    subCanal2: "Panaderia",
    codSubCanal1: "28",
    codSubCanal2: "38",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "29",
    subCanal1: "Otros",
    subCanal2: "Taller",
    codSubCanal1: "28",
    codSubCanal2: "39",
  },
  {
    sucursal: "S105",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "30",
    subCanal1: "Almacen/Despensa",
    subCanal2: "Almacen/Despensa",
    codSubCanal1: "00",
    codSubCanal2: "00",
  },
  {
    sucursal: "S105",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "30",
    subCanal1: "Almacen/Despensa",
    subCanal2: "Reja/Ventana",
    codSubCanal1: "00",
    codSubCanal2: "01",
  },
  {
    sucursal: "S105",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "30",
    subCanal1: "Kioskos Y Casillas",
    subCanal2: "Kioskos Y Casillas",
    codSubCanal1: "02",
    codSubCanal2: "02",
  },
  {
    sucursal: "S105",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "30",
    subCanal1: "Autoservicio",
    subCanal2: "Autoservicio",
    codSubCanal1: "03",
    codSubCanal2: "03",
  },
  {
    sucursal: "S105",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "30",
    subCanal1: "Minimercado",
    subCanal2: "Minimercado",
    codSubCanal1: "04",
    codSubCanal2: "04",
  },
  {
    sucursal: "S105",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "30",
    subCanal1: "Fruteria/Verduleria",
    subCanal2: "Fruteria/Verduleria",
    codSubCanal1: "05",
    codSubCanal2: "05",
  },
  {
    sucursal: "S105",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "30",
    subCanal1: "Limpieza",
    subCanal2: "Productos Caseros",
    codSubCanal1: "06",
    codSubCanal2: "07",
  },
  {
    sucursal: "S105",
    codigo: "10",
    canal: "Mayorista",
    listaPrecio: "51",
    subCanal1: "Mayorista Con Reparto",
    subCanal2: "Mayorista Con Reparto",
    codSubCanal1: "00",
    codSubCanal2: "00",
  },
  {
    sucursal: "S105",
    codigo: "10",
    canal: "Mayorista",
    listaPrecio: "51",
    subCanal1: "Mayorista con salon de ventas",
    subCanal2: "Mayorista con salon de ventas",
    codSubCanal1: "01",
    codSubCanal2: "01",
  },
  {
    sucursal: "S105",
    codigo: "10",
    canal: "Mayorista",
    listaPrecio: "51",
    subCanal1: "Comercial",
    subCanal2: "Comercial",
    codSubCanal1: "02",
    codSubCanal2: "02",
  },
  {
    sucursal: "S105",
    codigo: "10",
    canal: "Mayorista",
    listaPrecio: "51",
    subCanal1: "Comercial con reparto",
    subCanal2: "Comercial con reparto",
    codSubCanal1: "03",
    codSubCanal2: "03",
  },
  {
    sucursal: "S105",
    codigo: "02",
    canal: "Supermercado",
    listaPrecio: "50",
    subCanal1: "Skm Cadenas",
    subCanal2: "Skm Cadenas",
    codSubCanal1: "00",
    codSubCanal2: "00",
  },
  {
    sucursal: "S105",
    codigo: "02",
    canal: "Supermercado",
    listaPrecio: "50",
    subCanal1: "Skm independiente",
    subCanal2: "Skm independiente",
    codSubCanal1: "23",
    codSubCanal2: "23",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Hoteles",
    subCanal2: "Hoteles",
    codSubCanal1: "00",
    codSubCanal2: "00",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Moteles",
    subCanal2: "Moteles",
    codSubCanal1: "01",
    codSubCanal2: "01",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Posada",
    subCanal2: "Posada",
    codSubCanal1: "02",
    codSubCanal2: "02",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Lavanderias",
    subCanal2: "Lavanderias",
    codSubCanal1: "03",
    codSubCanal2: "03",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Estacion de servicio",
    subCanal2: "Estacion de servicio",
    codSubCanal1: "04",
    codSubCanal2: "04",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Farmacia",
    subCanal2: "Farmacia",
    codSubCanal1: "05",
    codSubCanal2: "05",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Veterinaria",
    subCanal2: "Veterinaria",
    codSubCanal1: "06",
    codSubCanal2: "06",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Spa-Peluquerias",
    subCanal2: "Spa-Peluquerias",
    codSubCanal1: "07",
    codSubCanal2: "07",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Empleados",
    subCanal2: "Empleados",
    codSubCanal1: "08",
    codSubCanal2: "08",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Club Social",
    subCanal2: "Club Social",
    codSubCanal1: "09",
    codSubCanal2: "09",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Hospitales/ Sanatorios",
    subCanal2: "Hospital",
    codSubCanal1: "10",
    codSubCanal2: "10",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Hospitales/ Sanatorios",
    subCanal2: "Sanatorio",
    codSubCanal1: "10",
    codSubCanal2: "11",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Instituciones",
    subCanal2: "Colegio",
    codSubCanal1: "12",
    codSubCanal2: "12",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Instituciones",
    subCanal2: "Guarderia",
    codSubCanal1: "12",
    codSubCanal2: "13",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Instituciones",
    subCanal2: "Escuela",
    codSubCanal1: "12",
    codSubCanal2: "14",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Instituciones",
    subCanal2: "Iglesia",
    codSubCanal1: "12",
    codSubCanal2: "15",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Instituciones",
    subCanal2: "Fundacion",
    codSubCanal1: "12",
    codSubCanal2: "16",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Empresas",
    subCanal2: "Limpieza",
    codSubCanal1: "17",
    codSubCanal2: "17",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Empresas",
    subCanal2: "Banco",
    codSubCanal1: "17",
    codSubCanal2: "18",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Empresas",
    subCanal2: "Cooperativa",
    codSubCanal1: "17",
    codSubCanal2: "19",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Empresas",
    subCanal2: "Fabrica",
    codSubCanal1: "17",
    codSubCanal2: "20",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Empresas",
    subCanal2: "Materiales de Construccion",
    codSubCanal1: "17",
    codSubCanal2: "21",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Bar",
    codSubCanal1: "22",
    codSubCanal2: "22",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Cafeteria",
    codSubCanal1: "22",
    codSubCanal2: "23",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Cantina",
    codSubCanal1: "22",
    codSubCanal2: "24",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Comedor",
    codSubCanal1: "22",
    codSubCanal2: "25",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Copetin",
    codSubCanal1: "22",
    codSubCanal2: "26",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Restaurant",
    codSubCanal1: "22",
    codSubCanal2: "27",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Otros",
    subCanal2: "Bodega",
    codSubCanal1: "28",
    codSubCanal2: "28",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Otros",
    subCanal2: "Carniceria",
    codSubCanal1: "28",
    codSubCanal2: "29",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Otros",
    subCanal2: "Consumidor Final",
    codSubCanal1: "28",
    codSubCanal2: "30",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Otros",
    subCanal2: "Consumo Interno",
    codSubCanal1: "28",
    codSubCanal2: "31",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Otros",
    subCanal2: "Ferreteria",
    codSubCanal1: "28",
    codSubCanal2: "32",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Otros",
    subCanal2: "Gomeria",
    codSubCanal1: "28",
    codSubCanal2: "33",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Otros",
    subCanal2: "Hamburgeseria",
    codSubCanal1: "28",
    codSubCanal2: "34",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Otros",
    subCanal2: "Heladeria",
    codSubCanal1: "28",
    codSubCanal2: "35",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Otros",
    subCanal2: "Librería",
    codSubCanal1: "28",
    codSubCanal2: "36",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Otros",
    subCanal2: "Merceria",
    codSubCanal1: "28",
    codSubCanal2: "37",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Otros",
    subCanal2: "Panaderia",
    codSubCanal1: "28",
    codSubCanal2: "38",
  },
  {
    sucursal: "S105",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "30",
    subCanal1: "Otros",
    subCanal2: "Taller",
    codSubCanal1: "28",
    codSubCanal2: "39",
  },
  {
    sucursal: "S104",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "36",
    subCanal1: "Almacen/Despensa",
    subCanal2: "Almacen/Despensa",
    codSubCanal1: "00",
    codSubCanal2: "00",
  },
  {
    sucursal: "S104",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "36",
    subCanal1: "Almacen/Despensa",
    subCanal2: "Reja/Ventana",
    codSubCanal1: "00",
    codSubCanal2: "01",
  },
  {
    sucursal: "S104",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "36",
    subCanal1: "Kioskos Y Casillas",
    subCanal2: "Kioskos Y Casillas",
    codSubCanal1: "02",
    codSubCanal2: "02",
  },
  {
    sucursal: "S104",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "36",
    subCanal1: "Autoservicio",
    subCanal2: "Autoservicio",
    codSubCanal1: "03",
    codSubCanal2: "03",
  },
  {
    sucursal: "S104",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "36",
    subCanal1: "Minimercado",
    subCanal2: "Minimercado",
    codSubCanal1: "04",
    codSubCanal2: "04",
  },
  {
    sucursal: "S104",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "36",
    subCanal1: "Fruteria/Verduleria",
    subCanal2: "Fruteria/Verduleria",
    codSubCanal1: "05",
    codSubCanal2: "05",
  },
  {
    sucursal: "S104",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "36",
    subCanal1: "Limpieza",
    subCanal2: "Productos Caseros",
    codSubCanal1: "06",
    codSubCanal2: "07",
  },
  {
    sucursal: "S104",
    codigo: "10",
    canal: "Mayorista",
    listaPrecio: "24",
    subCanal1: "Mayorista Con Reparto",
    subCanal2: "Mayorista Con Reparto",
    codSubCanal1: "00",
    codSubCanal2: "00",
  },
  {
    sucursal: "S104",
    codigo: "10",
    canal: "Mayorista",
    listaPrecio: "24",
    subCanal1: "Mayorista con salon de ventas",
    subCanal2: "Mayorista con salon de ventas",
    codSubCanal1: "01",
    codSubCanal2: "01",
  },
  {
    sucursal: "S104",
    codigo: "10",
    canal: "Mayorista",
    listaPrecio: "24",
    subCanal1: "Comercial",
    subCanal2: "Comercial",
    codSubCanal1: "02",
    codSubCanal2: "02",
  },
  {
    sucursal: "S104",
    codigo: "10",
    canal: "Mayorista",
    listaPrecio: "24",
    subCanal1: "Comercial con reparto",
    subCanal2: "Comercial con reparto",
    codSubCanal1: "03",
    codSubCanal2: "03",
  },
  {
    sucursal: "S104",
    codigo: "02",
    canal: "Supermercado",
    listaPrecio: "46",
    subCanal1: "Skm Cadenas",
    subCanal2: "Skm Cadenas",
    codSubCanal1: "00",
    codSubCanal2: "00",
  },
  {
    sucursal: "S104",
    codigo: "02",
    canal: "Supermercado",
    listaPrecio: "46",
    subCanal1: "Skm independiente",
    subCanal2: "Skm independiente",
    codSubCanal1: "23",
    codSubCanal2: "23",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Hoteles",
    subCanal2: "Hoteles",
    codSubCanal1: "00",
    codSubCanal2: "00",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Moteles",
    subCanal2: "Moteles",
    codSubCanal1: "01",
    codSubCanal2: "01",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Posada",
    subCanal2: "Posada",
    codSubCanal1: "02",
    codSubCanal2: "02",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Lavanderias",
    subCanal2: "Lavanderias",
    codSubCanal1: "03",
    codSubCanal2: "03",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Estacion de servicio",
    subCanal2: "Estacion de servicio",
    codSubCanal1: "04",
    codSubCanal2: "04",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Farmacia",
    subCanal2: "Farmacia",
    codSubCanal1: "05",
    codSubCanal2: "05",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Veterinaria",
    subCanal2: "Veterinaria",
    codSubCanal1: "06",
    codSubCanal2: "06",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Spa-Peluquerias",
    subCanal2: "Spa-Peluquerias",
    codSubCanal1: "07",
    codSubCanal2: "07",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Empleados",
    subCanal2: "Empleados",
    codSubCanal1: "08",
    codSubCanal2: "08",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Club Social",
    subCanal2: "Club Social",
    codSubCanal1: "09",
    codSubCanal2: "09",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Hospitales/ Sanatorios",
    subCanal2: "Hospital",
    codSubCanal1: "10",
    codSubCanal2: "10",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Hospitales/ Sanatorios",
    subCanal2: "Sanatorio",
    codSubCanal1: "10",
    codSubCanal2: "11",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Instituciones",
    subCanal2: "Colegio",
    codSubCanal1: "12",
    codSubCanal2: "12",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Instituciones",
    subCanal2: "Guarderia",
    codSubCanal1: "12",
    codSubCanal2: "13",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Instituciones",
    subCanal2: "Escuela",
    codSubCanal1: "12",
    codSubCanal2: "14",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Instituciones",
    subCanal2: "Iglesia",
    codSubCanal1: "12",
    codSubCanal2: "15",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Instituciones",
    subCanal2: "Fundacion",
    codSubCanal1: "12",
    codSubCanal2: "16",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Empresas",
    subCanal2: "Limpieza",
    codSubCanal1: "17",
    codSubCanal2: "17",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Empresas",
    subCanal2: "Banco",
    codSubCanal1: "17",
    codSubCanal2: "18",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Empresas",
    subCanal2: "Cooperativa",
    codSubCanal1: "17",
    codSubCanal2: "19",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Empresas",
    subCanal2: "Fabrica",
    codSubCanal1: "17",
    codSubCanal2: "20",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Empresas",
    subCanal2: "Materiales de Construccion",
    codSubCanal1: "17",
    codSubCanal2: "21",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Bar",
    codSubCanal1: "22",
    codSubCanal2: "22",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Cafeteria",
    codSubCanal1: "22",
    codSubCanal2: "23",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Cantina",
    codSubCanal1: "22",
    codSubCanal2: "24",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Comedor",
    codSubCanal1: "22",
    codSubCanal2: "25",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Copetin",
    codSubCanal1: "22",
    codSubCanal2: "26",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Restaurant",
    codSubCanal1: "22",
    codSubCanal2: "27",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Otros",
    subCanal2: "Bodega",
    codSubCanal1: "28",
    codSubCanal2: "28",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Otros",
    subCanal2: "Carniceria",
    codSubCanal1: "28",
    codSubCanal2: "29",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Otros",
    subCanal2: "Consumidor Final",
    codSubCanal1: "28",
    codSubCanal2: "30",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Otros",
    subCanal2: "Consumo Interno",
    codSubCanal1: "28",
    codSubCanal2: "31",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Otros",
    subCanal2: "Ferreteria",
    codSubCanal1: "28",
    codSubCanal2: "32",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Otros",
    subCanal2: "Gomeria",
    codSubCanal1: "28",
    codSubCanal2: "33",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Otros",
    subCanal2: "Hamburgeseria",
    codSubCanal1: "28",
    codSubCanal2: "34",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Otros",
    subCanal2: "Heladeria",
    codSubCanal1: "28",
    codSubCanal2: "35",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Otros",
    subCanal2: "Librería",
    codSubCanal1: "28",
    codSubCanal2: "36",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Otros",
    subCanal2: "Merceria",
    codSubCanal1: "28",
    codSubCanal2: "37",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Otros",
    subCanal2: "Panaderia",
    codSubCanal1: "28",
    codSubCanal2: "38",
  },
  {
    sucursal: "S104",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "36",
    subCanal1: "Otros",
    subCanal2: "Taller",
    codSubCanal1: "28",
    codSubCanal2: "39",
  },
  {
    sucursal: "S107",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "37",
    subCanal1: "Almacen/Despensa",
    subCanal2: "Almacen/Despensa",
    codSubCanal1: "00",
    codSubCanal2: "00",
  },
  {
    sucursal: "S107",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "37",
    subCanal1: "Almacen/Despensa",
    subCanal2: "Reja/Ventana",
    codSubCanal1: "00",
    codSubCanal2: "01",
  },
  {
    sucursal: "S107",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "37",
    subCanal1: "Kioskos Y Casillas",
    subCanal2: "Kioskos Y Casillas",
    codSubCanal1: "02",
    codSubCanal2: "02",
  },
  {
    sucursal: "S107",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "37",
    subCanal1: "Autoservicio",
    subCanal2: "Autoservicio",
    codSubCanal1: "03",
    codSubCanal2: "03",
  },
  {
    sucursal: "S107",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "37",
    subCanal1: "Minimercado",
    subCanal2: "Minimercado",
    codSubCanal1: "04",
    codSubCanal2: "04",
  },
  {
    sucursal: "S107",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "37",
    subCanal1: "Fruteria/Verduleria",
    subCanal2: "Fruteria/Verduleria",
    codSubCanal1: "05",
    codSubCanal2: "05",
  },
  {
    sucursal: "S107",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "37",
    subCanal1: "Limpieza",
    subCanal2: "Productos Caseros",
    codSubCanal1: "06",
    codSubCanal2: "07",
  },
  {
    sucursal: "S107",
    codigo: "10",
    canal: "Mayorista",
    listaPrecio: "40",
    subCanal1: "Mayorista Con Reparto",
    subCanal2: "Mayorista Con Reparto",
    codSubCanal1: "00",
    codSubCanal2: "00",
  },
  {
    sucursal: "S107",
    codigo: "10",
    canal: "Mayorista",
    listaPrecio: "40",
    subCanal1: "Mayorista con salon de ventas",
    subCanal2: "Mayorista con salon de ventas",
    codSubCanal1: "01",
    codSubCanal2: "01",
  },
  {
    sucursal: "S107",
    codigo: "10",
    canal: "Mayorista",
    listaPrecio: "40",
    subCanal1: "Comercial",
    subCanal2: "Comercial",
    codSubCanal1: "02",
    codSubCanal2: "02",
  },
  {
    sucursal: "S107",
    codigo: "10",
    canal: "Mayorista",
    listaPrecio: "40",
    subCanal1: "Comercial con reparto",
    subCanal2: "Comercial con reparto",
    codSubCanal1: "03",
    codSubCanal2: "03",
  },
  {
    sucursal: "S107",
    codigo: "02",
    canal: "Supermercado",
    listaPrecio: "47",
    subCanal1: "Skm Cadenas",
    subCanal2: "Skm Cadenas",
    codSubCanal1: "00",
    codSubCanal2: "00",
  },
  {
    sucursal: "S107",
    codigo: "02",
    canal: "Supermercado",
    listaPrecio: "47",
    subCanal1: "Skm independiente",
    subCanal2: "Skm independiente",
    codSubCanal1: "23",
    codSubCanal2: "23",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Hoteles",
    subCanal2: "Hoteles",
    codSubCanal1: "00",
    codSubCanal2: "00",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Moteles",
    subCanal2: "Moteles",
    codSubCanal1: "01",
    codSubCanal2: "01",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Posada",
    subCanal2: "Posada",
    codSubCanal1: "02",
    codSubCanal2: "02",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Lavanderias",
    subCanal2: "Lavanderias",
    codSubCanal1: "03",
    codSubCanal2: "03",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Estacion de servicio",
    subCanal2: "Estacion de servicio",
    codSubCanal1: "04",
    codSubCanal2: "04",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Farmacia",
    subCanal2: "Farmacia",
    codSubCanal1: "05",
    codSubCanal2: "05",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Veterinaria",
    subCanal2: "Veterinaria",
    codSubCanal1: "06",
    codSubCanal2: "06",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Spa-Peluquerias",
    subCanal2: "Spa-Peluquerias",
    codSubCanal1: "07",
    codSubCanal2: "07",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Empleados",
    subCanal2: "Empleados",
    codSubCanal1: "08",
    codSubCanal2: "08",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Club Social",
    subCanal2: "Club Social",
    codSubCanal1: "09",
    codSubCanal2: "09",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Hospitales/ Sanatorios",
    subCanal2: "Hospital",
    codSubCanal1: "10",
    codSubCanal2: "10",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Hospitales/ Sanatorios",
    subCanal2: "Sanatorio",
    codSubCanal1: "10",
    codSubCanal2: "11",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Instituciones",
    subCanal2: "Colegio",
    codSubCanal1: "12",
    codSubCanal2: "12",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Instituciones",
    subCanal2: "Guarderia",
    codSubCanal1: "12",
    codSubCanal2: "13",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Instituciones",
    subCanal2: "Escuela",
    codSubCanal1: "12",
    codSubCanal2: "14",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Instituciones",
    subCanal2: "Iglesia",
    codSubCanal1: "12",
    codSubCanal2: "15",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Instituciones",
    subCanal2: "Fundacion",
    codSubCanal1: "12",
    codSubCanal2: "16",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Empresas",
    subCanal2: "Limpieza",
    codSubCanal1: "17",
    codSubCanal2: "17",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Empresas",
    subCanal2: "Banco",
    codSubCanal1: "17",
    codSubCanal2: "18",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Empresas",
    subCanal2: "Cooperativa",
    codSubCanal1: "17",
    codSubCanal2: "19",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Empresas",
    subCanal2: "Fabrica",
    codSubCanal1: "17",
    codSubCanal2: "20",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Empresas",
    subCanal2: "Materiales de Construccion",
    codSubCanal1: "17",
    codSubCanal2: "21",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Bar",
    codSubCanal1: "22",
    codSubCanal2: "22",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Cafeteria",
    codSubCanal1: "22",
    codSubCanal2: "23",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Cantina",
    codSubCanal1: "22",
    codSubCanal2: "24",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Comedor",
    codSubCanal1: "22",
    codSubCanal2: "25",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Copetin",
    codSubCanal1: "22",
    codSubCanal2: "26",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Restaurant",
    codSubCanal1: "22",
    codSubCanal2: "27",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Otros",
    subCanal2: "Bodega",
    codSubCanal1: "28",
    codSubCanal2: "28",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Otros",
    subCanal2: "Carniceria",
    codSubCanal1: "28",
    codSubCanal2: "29",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Otros",
    subCanal2: "Consumidor Final",
    codSubCanal1: "28",
    codSubCanal2: "30",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Otros",
    subCanal2: "Consumo Interno",
    codSubCanal1: "28",
    codSubCanal2: "31",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Otros",
    subCanal2: "Ferreteria",
    codSubCanal1: "28",
    codSubCanal2: "32",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Otros",
    subCanal2: "Gomeria",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Otros",
    subCanal2: "Hamburgeseria",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Otros",
    subCanal2: "Heladeria",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Otros",
    subCanal2: "Librería",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Otros",
    subCanal2: "Merceria",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Otros",
    subCanal2: "Panaderia",
  },
  {
    sucursal: "S107",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "37",
    subCanal1: "Otros",
    subCanal2: "Taller",
  },
  {
    sucursal: "S106",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "23",
    subCanal1: "Almacen/Despensa",
    subCanal2: "Almacen/Despensa",
  },
  {
    sucursal: "S106",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "23",
    subCanal1: "Almacen/Despensa",
    subCanal2: "Reja/Ventana",
  },
  {
    sucursal: "S106",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "23",
    subCanal1: "Kioskos Y Casillas",
    subCanal2: "Kioskos Y Casillas",
  },
  {
    sucursal: "S106",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "23",
    subCanal1: "Autoservicio",
    subCanal2: "Autoservicio",
  },
  {
    sucursal: "S106",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "23",
    subCanal1: "Minimercado",
    subCanal2: "Minimercado",
    codSubCanal1: "04",
    codSubCanal2: "04",
  },
  {
    sucursal: "S106",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "23",
    subCanal1: "Fruteria/Verduleria",
    subCanal2: "Fruteria/Verduleria",
    codSubCanal1: "05",
    codSubCanal2: "05",
  },
  {
    sucursal: "S106",
    codigo: "01",
    canal: "Minorista",
    listaPrecio: "23",
    subCanal1: "Limpieza",
    subCanal2: "Productos Caseros",
    codSubCanal1: "06",
    codSubCanal2: "07",
  },
  {
    sucursal: "S106",
    codigo: "10",
    canal: "Mayorista",
    listaPrecio: "27",
    subCanal1: "Mayorista Con Reparto",
    subCanal2: "Mayorista Con Reparto",
  },
  {
    sucursal: "S106",
    codigo: "10",
    canal: "Mayorista",
    listaPrecio: "27",
    subCanal1: "Mayorista con salon de ventas",
    subCanal2: "Mayorista con salon de ventas",
    codSubCanal1: "01",
    codSubCanal2: "01",
  },
  {
    sucursal: "S106",
    codigo: "10",
    canal: "Mayorista",
    listaPrecio: "27",
    subCanal1: "Comercial",
    subCanal2: "Comercial",
    codSubCanal1: "02",
    codSubCanal2: "02",
  },
  {
    sucursal: "S106",
    codigo: "10",
    canal: "Mayorista",
    listaPrecio: "27",
    subCanal1: "Comercial con reparto",
    subCanal2: "Comercial con reparto",
    codSubCanal1: "03",
    codSubCanal2: "03",
  },
  {
    sucursal: "S106",
    codigo: "02",
    canal: "Supermercado",
    listaPrecio: "28",
    subCanal1: "Skm Cadenas",
    subCanal2: "Skm Cadenas",
    codSubCanal1: "00",
    codSubCanal2: "00",
  },
  {
    sucursal: "S106",
    codigo: "02",
    canal: "Supermercado",
    listaPrecio: "28",
    subCanal1: "Skm independiente",
    subCanal2: "Skm independiente",
    codSubCanal1: "23",
    codSubCanal2: "23",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Hoteles",
    subCanal2: "Hoteles",
    codSubCanal1: "00",
    codSubCanal2: "00",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Moteles",
    subCanal2: "Moteles",
    codSubCanal1: "01",
    codSubCanal2: "01",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Posada",
    subCanal2: "Posada",
    codSubCanal1: "02",
    codSubCanal2: "02",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Lavanderias",
    subCanal2: "Lavanderias",
    codSubCanal1: "03",
    codSubCanal2: "03",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Estacion de servicio",
    subCanal2: "Estacion de servicio",
    codSubCanal1: "04",
    codSubCanal2: "04",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Farmacia",
    subCanal2: "Farmacia",
    codSubCanal1: "05",
    codSubCanal2: "05",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Veterinaria",
    subCanal2: "Veterinaria",
    codSubCanal1: "06",
    codSubCanal2: "06",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Spa-Peluquerias",
    subCanal2: "Spa-Peluquerias",
    codSubCanal1: "07",
    codSubCanal2: "07",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Empleados",
    subCanal2: "Empleados",
    codSubCanal1: "08",
    codSubCanal2: "08",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Club Social",
    subCanal2: "Club Social",
    codSubCanal1: "09",
    codSubCanal2: "09",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Hospitales/ Sanatorios",
    subCanal2: "Hospital",
    codSubCanal1: "10",
    codSubCanal2: "10",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Hospitales/ Sanatorios",
    subCanal2: "Sanatorio",
    codSubCanal1: "10",
    codSubCanal2: "11",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Instituciones",
    subCanal2: "Colegio",
    codSubCanal1: "12",
    codSubCanal2: "12",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Instituciones",
    subCanal2: "Guarderia",
    codSubCanal1: "12",
    codSubCanal2: "13",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Instituciones",
    subCanal2: "Escuela",
    codSubCanal1: "12",
    codSubCanal2: "14",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Instituciones",
    subCanal2: "Iglesia",
    codSubCanal1: "12",
    codSubCanal2: "15",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Instituciones",
    subCanal2: "Fundacion",
    codSubCanal1: "12",
    codSubCanal2: "16",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Empresas",
    subCanal2: "Limpieza",
    codSubCanal1: "17",
    codSubCanal2: "17",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Empresas",
    subCanal2: "Banco",
    codSubCanal1: "17",
    codSubCanal2: "18",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Empresas",
    subCanal2: "Cooperativa",
    codSubCanal1: "17",
    codSubCanal2: "19",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Empresas",
    subCanal2: "Fabrica",
    codSubCanal1: "17",
    codSubCanal2: "20",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Empresas",
    subCanal2: "Materiales de Construccion",
    codSubCanal1: "17",
    codSubCanal2: "21",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Bar",
    codSubCanal1: "22",
    codSubCanal2: "22",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Cafeteria",
    codSubCanal1: "22",
    codSubCanal2: "23",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Cantina",
    codSubCanal1: "22",
    codSubCanal2: "24",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Comedor",
    codSubCanal1: "22",
    codSubCanal2: "25",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Copetin",
    codSubCanal1: "22",
    codSubCanal2: "26",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Restaurantes y Comedor",
    subCanal2: "Restaurant",
    codSubCanal1: "22",
    codSubCanal2: "27",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Otros",
    subCanal2: "Bodega",
    codSubCanal1: "28",
    codSubCanal2: "28",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Otros",
    subCanal2: "Carniceria",
    codSubCanal1: "28",
    codSubCanal2: "29",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Otros",
    subCanal2: "Consumidor Final",
    codSubCanal1: "28",
    codSubCanal2: "30",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Otros",
    subCanal2: "Consumo Interno",
    codSubCanal1: "28",
    codSubCanal2: "31",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Otros",
    subCanal2: "Ferreteria",
    codSubCanal1: "28",
    codSubCanal2: "32",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Otros",
    subCanal2: "Gomeria",
    codSubCanal1: "28",
    codSubCanal2: "33",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Otros",
    subCanal2: "Hamburgeseria",
    codSubCanal1: "28",
    codSubCanal2: "34",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Otros",
    subCanal2: "Heladeria",
    codSubCanal1: "28",
    codSubCanal2: "35",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Otros",
    subCanal2: "Librería",
    codSubCanal1: "28",
    codSubCanal2: "36",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Otros",
    subCanal2: "Merceria",
    codSubCanal1: "28",
    codSubCanal2: "37",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Otros",
    subCanal2: "Panaderia",
    codSubCanal1: "28",
    codSubCanal2: "38",
  },
  {
    sucursal: "S106",
    codigo: "09",
    canal: "Institucional- B2B",
    listaPrecio: "23",
    subCanal1: "Otros",
    subCanal2: "Taller",
    codSubCanal1: "28",
    codSubCanal2: "39",
  },
];
